# This file was generated by GoReleaser. DO NOT EDIT.
cask "portly" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "89aeab082fcf927f7f699f2a1fdc186fbcb6ab1b70d0249e00abcb54166293a0"
      url "https://github.com/velvet-tiger/portly/releases/download/v#{version}/portly_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0f80303767128fc84ce19d33b7e51417bdc38daad57b89deb901766b9074ca81"
      url "https://github.com/velvet-tiger/portly/releases/download/v#{version}/portly_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cc2be75ff2cf7df050eb41b8d78a049f2b5451676bf498d693673567c02fd672"
      url "https://github.com/velvet-tiger/portly/releases/download/v#{version}/portly_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6b0db4f48b0b070baffc841ea655bc6c1e12771ab5ae4a6d795ef608df61d227"
      url "https://github.com/velvet-tiger/portly/releases/download/v#{version}/portly_#{version}_linux_arm64.tar.gz"
    end
  end

  name "portly"
  desc "Finds the development servers running on your machine"
  homepage "https://github.com/velvet-tiger/portly"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "portly"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/portly"]
    end
  end

  # No zap stanza required

end
