# This file was generated by GoReleaser. DO NOT EDIT.
cask "portly" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "588dbe4c9e93a8b99cf668c8bc1599c67581ec3407c0e8c366536d3b0137efd7"
      url "https://github.com/velvet-tiger/portly/releases/download/v#{version}/portly_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7af0821483a7d6c5b5cebc5ed585191c39f6ef93f08f2ea622e04897173f8c50"
      url "https://github.com/velvet-tiger/portly/releases/download/v#{version}/portly_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "portly"
  desc "Finds the development servers running on your machine"
  homepage "https://github.com/velvet-tiger/portly"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "portly"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/portly"]
    end
  end

  # No zap stanza required

end
