# This file was generated by GoReleaser. DO NOT EDIT.
cask "portly" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "6f34b4a11bf550aeb4d29d6bcd7db173484c87fbbe824d0f2dc5b8de8abaabb5"
      url "https://github.com/velvet-tiger/portly/releases/download/v#{version}/portly_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6f0984232767d0d8332b846ecf599baa22d06074f8516d87d44a6d602424926b"
      url "https://github.com/velvet-tiger/portly/releases/download/v#{version}/portly_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "portly"
  desc "Finds the development servers running on your machine"
  homepage "https://github.com/velvet-tiger/portly"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "portly"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/portly"]
    end
  end

  # No zap stanza required

end
